# Generated by Django 5.0.6 on 2024-08-07 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataSave', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangerate',
            name='high',
        ),
        migrations.RemoveField(
            model_name='exchangerate',
            name='low',
        ),
        migrations.RemoveField(
            model_name='exchangerate',
            name='open',
        ),
        migrations.RemoveField(
            model_name='exchangerate',
            name='volume',
        ),
    ]
