# Generated by Django 5.0.6 on 2024-07-31 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('industry_code', models.CharField(max_length=20)),
                ('industry', models.CharField(max_length=100)),
                ('exchange', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=10)),
            ],
        ),
    ]
